# Generated by Django 4.1.2 on 2024-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='number',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
