# Generated by Django 4.1.2 on 2024-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='email',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='msg',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='phone',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='product_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
