# Generated by Django 4.1.2 on 2024-06-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productrequest_email_alter_productrequest_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
