# Generated by Django 4.1.2 on 2024-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_cate_alter_products_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ad_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='detailed_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
